### ISSUE TITLE
Multiple source file support

### ISSUE THREAD

**Issue by eholk** [brson/mir2wasm#29]
How do we want these to work? One Rust module per Wasm module? One Wasm module per crate? How do we decide what is exported to Wasm?

**Comment by eddyb** [comment]
I believe multiple files are already supported, and if you follow the LLVM model, you will want one wasm module per crate.
[The relevant part of deciding what's exported](https://github.com/rust-lang/rust/blob/27e766d7bc84be992c8ddef710affc92ef4a0adf/src/librustc_trans/base.rs#L2391-L2449) from current LLVM trans is mostly using information already computed in the compiler, and filtering out some cases which are never exported.

**Comment by eholk** [comment]
#32 shows we have support for this (although multiple crates are probably a different issue), so I'm going to go ahead and close this.
